services:
  - type: web
    name: seismic-auth-api
    env: python
    region: oregon
    rootDirectory: Backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn combined_asgi:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /healthz
    autoDeploy: true
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: CORS_ALLOWED_ORIGINS
        value: https://prediccion-de-sismos-facial-v1.vercel.app,http://localhost:3000
      - key: DJANGO_ALLOWED_HOSTS
        value: prediccion-de-sismos-facial-v1.onrender.com,localhost,127.0.0.1
      # Si usas DB gestionada, descomenta y coloca tu cadena
      # - key: DATABASE_URL
      #   value: mysql://user:pass@host:3306/dbname
